### ISSUE TITLE
FxCop deprecation warning in VS2019

### ISSUE THREAD

**Issue by asquigglytwist** [asquigglytwist/Tyle#7]
Below warning gets displayed after build in **VS 2019**.

> **CA0507**
> Post-build Code Analysis (FxCopCmd.exe) has been deprecated in favor of FxCop analyzers, which run during build. Refer to https://aka.ms/fxcopanalyzers to migrate to FxCop analyzers.
>

**Comment by A9G-Data-Droid** [comment]
I installed the Nuget Package `Microsoft.CodeAnalysis.NetAnalyzers`

I set `<RunCodeAnalysis>false</RunCodeAnalysis>` like it says in https://docs.microsoft.com/en-us/visualstudio/code-quality/migrate-from-legacy-analysis-to-net-analyzers?WT.mc_id=visualstudio_codeanalysis_aka_fxcopanalyzers&view=vs-2019

I also checked the checkbox is showing unchecked:
![image](https://user-images.githubusercontent.com/26984068/138345958-c1fc1217-e6b6-43aa-8660-a5780ba77eb6.png)

I still see the warning. I can't seem to find any other guidance on how to clear this warning. I even opened the project in Visual Studio 2022 Preview and the warning is still there when I attempt to Analyze the project.
